BEGIN;
--ROLLBACK;


DROP TABLE IF EXISTS dev."User" CASCADE;
DROP TABLE IF EXISTS dev."User_info" CASCADE;
DROP TABLE IF EXISTS dev."User_info_type" CASCADE;
DROP TABLE IF EXISTS dev."User_status" CASCADE;
DROP TABLE IF EXISTS dev."User_avatar" CASCADE;
DROP TABLE IF EXISTS dev."Company" CASCADE;
DROP TABLE IF EXISTS dev."Company_info" CASCADE;
DROP TABLE IF EXISTS dev."Company_info_type" CASCADE;
DROP TABLE IF EXISTS dev."Company_status" CASCADE;
DROP TABLE IF EXISTS dev."Company_avatar" CASCADE;
DROP TABLE IF EXISTS dev."Company_alias" CASCADE;
DROP TABLE IF EXISTS dev."Shelter" CASCADE;
DROP TABLE IF EXISTS dev."Shelter_type" CASCADE;
DROP TABLE IF EXISTS dev."Shelter_info" CASCADE;
DROP TABLE IF EXISTS dev."Shelter_info_type" CASCADE;
DROP TABLE IF EXISTS dev."Shelter_status" CASCADE;
DROP TABLE IF EXISTS dev."Shelter_avatar" CASCADE;
DROP TABLE IF EXISTS dev."Tag" CASCADE;
DROP TABLE IF EXISTS dev."Event" CASCADE;
DROP TABLE IF EXISTS dev."Event_info" CASCADE;
DROP TABLE IF EXISTS dev."Event_info_type" CASCADE;
DROP TABLE IF EXISTS dev."UserToCompany" CASCADE;
DROP TABLE IF EXISTS dev."CompanyToEvent" CASCADE;
DROP TABLE IF EXISTS dev."UserToEvent" CASCADE;
DROP TABLE IF EXISTS dev."TagToShelter" CASCADE;

CREATE TABLE dev."User" (
	id SERIAL NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	pass_hash VARCHAR NOT NULL,
	phone_num VARCHAR(20) NOT NULL,
	status_id INTEGER NOT NULL,
	avatar_id INTEGER,
	is_superuser BOOLEAN NOT NULL,
	locale_lang VARCHAR(20) DEFAULT 'ru',
	created_date TIMESTAMP NOT NULL,
	created_by_id INTEGER,
	last_modified_date TIMESTAMP NOT NULL,
	last_modified_by_id INTEGER,
	PRIMARY KEY (id),
	UNIQUE (email, phone_num)
);

CREATE TABLE dev."User_info" (
	id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	info VARCHAR(255) NOT NULL,
	info_type_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."User_info_type" (
	id SERIAL NOT NULL,
	type VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."User_status" (
	id SERIAL NOT NULL,
	title VARCHAR(20) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."User_avatar" (
	id SERIAL NOT NULL,
	avatar BYTEA NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Company" (
	id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	status_id INTEGER NOT NULL,
	avatar_id INTEGER,
	created_date TIMESTAMP NOT NULL,
	created_by_id INTEGER,
	last_modified_date TIMESTAMP NOT NULL,
	last_modified_by_id INTEGER,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."Company_info" (
	id SERIAL NOT NULL,
	company_id INTEGER NOT NULL,
	info VARCHAR(255) NOT NULL,
	info_type_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Company_info_type" (
	id SERIAL NOT NULL,
	type VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Company_status" (
	id SERIAL NOT NULL,
	title VARCHAR(20) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."Company_avatar" (
	id SERIAL NOT NULL,
	avatar BYTEA NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Company_alias" (
	id SERIAL NOT NULL,
	alias VARCHAR NOT NULL,
	company_id VARCHAR NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (alias)
);

CREATE TABLE dev."Shelter" (
	id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	type_id INTEGER NOT NULL,
	status_id INTEGER NOT NULL,
	avatar_id INTEGER,
	created_date TIMESTAMP NOT NULL,
	created_by_id INTEGER,
	last_modified_date TIMESTAMP NOT NULL,
	last_modified_by_id INTEGER,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."Shelter_type" (
	id SERIAL NOT NULL,
	title VARCHAR(20) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."Shelter_info" (
	id SERIAL NOT NULL,
	shelter_id INTEGER NOT NULL,
	info VARCHAR(255) NOT NULL,
	info_type_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Shelter_info_type" (
	id SERIAL NOT NULL,
	type VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Shelter_status" (
	id SERIAL NOT NULL,
	title VARCHAR(20) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."Shelter_avatar" (
	id SERIAL NOT NULL,
	avatar BYTEA NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Tag" (
	id SERIAL NOT NULL,
	title VARCHAR(50) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (title)
);

CREATE TABLE dev."Event" (
	id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	shelter_id INTEGER NOT NULL,
	date TIMESTAMP NOT NULL,
	is_accessable BOOLEAN NOT NULL,
	created_date TIMESTAMP NOT NULL,
	created_by_id INTEGER,
	last_modified_date TIMESTAMP NOT NULL,
	last_modified_by_id INTEGER,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Event_info" (
	id SERIAL NOT NULL,
	event_id INTEGER NOT NULL,
	info VARCHAR(255) NOT NULL,
	info_type_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."Event_info_type" (
	id SERIAL NOT NULL,
	type VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."UserToCompany" (
	id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	company_id INTEGER NOT NULL,
	is_admin BOOLEAN NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."CompanyToEvent" (
	id SERIAL NOT NULL,
	event_id INTEGER NOT NULL,
	company_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."UserToEvent" (
	id SERIAL NOT NULL,
	event_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE dev."TagToShelter" (
	id SERIAL NOT NULL,
	shelter_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	PRIMARY KEY (id)
);

ALTER TABLE dev."User" ADD FOREIGN KEY (status_id) REFERENCES dev."User_status"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."User" ADD FOREIGN KEY (avatar_id) REFERENCES dev."User_avatar"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE dev."User" ADD FOREIGN KEY (created_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."User" ADD FOREIGN KEY (last_modified_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."User_info" ADD FOREIGN KEY (user_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."User_info" ADD FOREIGN KEY (info_type_id) REFERENCES dev."User_info_type"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."Company" ADD FOREIGN KEY (status_id) REFERENCES dev."Company_status"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Company" ADD FOREIGN KEY (avatar_id) REFERENCES dev."Company_avatar"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE dev."Company" ADD FOREIGN KEY (created_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Company" ADD FOREIGN KEY (last_modified_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."Company_info" ADD FOREIGN KEY (company_id) REFERENCES dev."Company"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."Company_info" ADD FOREIGN KEY (info_type_id) REFERENCES dev."Company_info_type"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."Shelter" ADD FOREIGN KEY (status_id) REFERENCES dev."Shelter_status"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Shelter" ADD FOREIGN KEY (avatar_id) REFERENCES dev."Shelter_avatar"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE dev."Shelter" ADD FOREIGN KEY (type_id) REFERENCES dev."Shelter_type"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Shelter" ADD FOREIGN KEY (created_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Shelter" ADD FOREIGN KEY (last_modified_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."Shelter_info" ADD FOREIGN KEY (shelter_id) REFERENCES dev."Shelter"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."Shelter_info" ADD FOREIGN KEY (info_type_id) REFERENCES dev."Shelter_info_type"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."Event" ADD FOREIGN KEY (shelter_id) REFERENCES dev."Shelter"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Event" ADD FOREIGN KEY (created_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dev."Event" ADD FOREIGN KEY (last_modified_by_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."Event_info" ADD FOREIGN KEY (event_id) REFERENCES dev."Event"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."Event_info" ADD FOREIGN KEY (info_type_id) REFERENCES dev."Event_info_type"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE dev."UserToCompany" ADD FOREIGN KEY (user_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."UserToCompany" ADD FOREIGN KEY (company_id) REFERENCES dev."Company"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dev."CompanyToEvent" ADD FOREIGN KEY (event_id) REFERENCES dev."Event"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."CompanyToEvent" ADD FOREIGN KEY (company_id) REFERENCES dev."Company"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dev."UserToEvent" ADD FOREIGN KEY (event_id) REFERENCES dev."Event"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."UserToEvent" ADD FOREIGN KEY (user_id) REFERENCES dev."User"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dev."TagToShelter" ADD FOREIGN KEY (shelter_id) REFERENCES dev."Shelter"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE dev."TagToShelter" ADD FOREIGN KEY (tag_id) REFERENCES dev."Tag"(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;

COMMIT;